Name	Type	Data
(same as parent folder)	Start of Authority (SOA)	[33], iaas-170.corp.local., hostmaster.corp.local.
(same as parent folder)	Name Server (NS)	iaas-170.corp.local.
li	Host (A)	10.0.0.99
nsxm1	Host (A)	10.0.0.107
nsxr1	Host (A)	10.0.0.108
pscr1	Host (A)	10.0.0.103
rabbitmq-lb-0	Host (A)	10.0.0.120
rmq1	Host (A)	10.0.0.171
rmq2	Host (A)	10.0.0.172
vcav-cassandra1	Host (A)	10.0.0.175
vcav-cassandra2	Host (A)	10.0.0.176
vcav-cassandra3	Host (A)	10.0.0.177
vcav-portal1	Host (A)	10.0.8.14
vcav-portal2	Host (A)	10.0.8.15
vcav-proxy1	Host (A)	10.0.8.16
vcav-proxy2	Host (A)	10.0.8.17
vcd-nfs	Host (A)	10.0.8.21
vcdc1	Host (A)	10.0.8.2
vcdc2	Host (A)	10.0.8.3
vcdconsole1	Host (A)	10.0.8.4
vcdconsole2	Host (A)	10.0.8.5
vcddb1	Host (A)	10.0.0.206
vcm1	Host (A)	10.0.0.105
vcr1	Host (A)	10.0.0.106
vrcs1	Host (A)	10.0.0.157
vrcs2	Host (A)	10.0.0.158
vrm1	Host (A)	10.0.0.156
vrs1	Host (A)	10.0.0.166
vrs2	Host (A)	10.0.0.167
